version: "2"

services:
    web:
        build: .
        restart: "always"
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
        volumes:
            - ./src/:/app
            - static:/data/static
        env_file:
            - .env
    db:
        image: postgres:10.1-alpine
        restart: "always"
        volumes:
            - pgdata:/var/lib/postgresql/data/
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
    certbot:
        image: certbot/certbot
        restart: "always"
        volumes:
            - ./docker/nginx/certbot/conf:/etc/letsencrypt
            - ./docker/nginx/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    redis:
        image: redis:5.0.8
        restart: "always"
        expose:
            - "6379"
volumes:
     pgdata:
     static:
