version: '3'

services:
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
            - "2244:22"
        depends_on:
            - db
        volumes:
            - .:/code/
        working_dir: /code/
        env_file:
            - .env
    db:
        image: postgres:10
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}

volumes:
     pgdata: