version: "2"

services:
    web:
        build: .
        restart: "always"
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
        volumes:
            - ./src/:/app
            - static:/data/static
        env_file:
            - .env
    db:
        image: postgres:10.1-alpine
        restart: "always"
        ports:
            - "54321:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data/
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
    redis:
        image: redis:5.0.8
        restart: "always"
        expose:
            - "6379"
volumes:
     pgdata:
     static:
