# Generated by Django 3.0.3 on 2020-04-17 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_auto_20200331_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifylink',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='spotify.Album', verbose_name='Album'),
        ),
        migrations.AlterField(
            model_name='spotifylink',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='spotify.Artist', verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='spotifylink',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='spotify.Track', verbose_name='Track'),
        ),
    ]
