# Generated by Django 3.0.3 on 2020-04-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=250, verbose_name='Photo URL'),
        ),
    ]
