# Generated by Django 3.0.3 on 2020-04-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0003_auto_20200411_1406"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sentspotifylink",
            options={
                "verbose_name": "Sent Spotify Link",
                "verbose_name_plural": "Sent Spotify Links",
            },
        ),
    ]
